version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl_app:
    build:
      context: ./etl
    container_name: etl_app
    depends_on:
      - db
    volumes:
      - ./etl:/app
    command: python etl_script.py

volumes:
  postgres_data:
